authors:
  leonchuk:
    name: Женя Леончук
    description: Зам. ГК
    avatar: img/avatar/Leonchuk.webp
  diachkov:
    name: Саша Дьячков
    description: Инженер-программист АСУТП
    avatar: img/avatar/Diachkov.webp    